import "./global.scss";
import "./globals.css";
import "@/scss/custom/input.scss";
import "@/scss/custom/textarea.scss";
import "@/scss/custom/search.scss";
import "@/scss/custom/checkbox.scss";

import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";
import { cookies } from "next/headers";
import ClientLayout from "./ClientLayout";
import { StateProvider, User } from "@/providers/StateProvider";
import { ApolloProv } from "@/providers/ApoloProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata = {
  title: "Ulon",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const userCookie = cookieStore.get("user")?.value ?? null;
  const initialUser: User | null = userCookie ? JSON.parse(userCookie) : null;
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
      </head>
      <body>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}
        >
          <ApolloProv>
            <StateProvider initialUser={initialUser}>
              <ClientLayout>{children}</ClientLayout>
            </StateProvider>
          </ApolloProv>
        </GoogleOAuthProvider>
        <Analytics />
      </body>
    </html>
  );
}
